### ISSUE TITLE
Does spaCy ever use the AUX tag? (in the .pos_ field)

### ISSUE THREAD

**Issue by vaulttech** [explosion/spaCy#1113]
For something I'm doing, I am trying to check if the main verb of a sentence is a linking verb. The simplest way I thought for this was to check the POS Tag of the verb. I know that spaCy's tag set is based on the [Google Universal POS Tag set](http://universaldependencies.org/u/pos/AUX_.html), that has an `AUX` tag for (among other stuff) copulas.

But I noticed spaCy seems to always mark auxiliaries (or copulas) as `VERB`. For example:
``` python
In [40]: nlp = spacy.load('en_core_web_sm')
In [41]: doc = nlp('this is strange')
In [42]: doc[1].pos_
Out[42]: 'VERB'
```
or (in the case of the auxiliary indicating passive)
``` python
In [23]: doc = nlp('I was taken')
In [24]: doc[1].pos_
Out[24]: 'VERB'
```

I tried both the `en_core_web_sm` and the en_core_web_md` models. Am I doing something wrong?

## Your Environment
* **Python version:** 3.5.3
* **Installed models:** de, en, en_core_web_md
* **Platform:** Windows-7-6.1.7601-SP1
* **spaCy version:** 1.7.2

**Comment by notnami** [comment]
The AUX tag is used by the dependency parser. E.g. https://demos.explosion.ai/displacy/?text=Does%20this%20fly%3F&model=en&cpu=1&cph=1

**Comment by slavaGanzin** [comment]
Arrays starts at zero.

```
for word in doc:
    print(word.lemma_, word.pos_)

#-PRON- PRON
#be VERB
#take VERB
```

**Comment by honnibal** [comment]
The universal tag map is not quite consistent with either the Google universal set or the Universal Dependencies tags. There's an open issue about this that's never been quite resolved, because I didn't want to break things. This should be fixed for v2.

**Comment by vaulttech** [comment]
@notnami Hmm... but this is actually a coincidence. I mean, it is a coincidence that the tag set of the dependency parser also has an "aux" tag (notice also that this tag is not capital). For example, if I do:

``` python
doc = nlp("Does that fly?")
for i in doc:
    print(i, i.pos_, i.dep_)
```

I still see the "does" as a verb.

@honnibal Ohh... I am not sure if I understand. (I was actually just curious about this)

You are saying there are 3 tag sets that are similar but not exactly compatible with each other, all of which have the word "Universal" in their names? In fact, I couldn't actually find the Google tag set, nor any "Universal tag map"; I only found the [Universal POS tags](http://universaldependencies.org/u/pos/index.html#universal-pos-tags). Does the spaCy tag set comply 100% to any of these?

[I ended up generating some special rule to find out if there is a copula or not (not sure if it always works)]

**Comment by ines** [comment]
For the new docs, we've updated the annotation scheme for the different languages, including the mapping of `.pos_` and `.tag_`: https://spacy.io/api/annotation#pos-tagging This is the annotation scheme used across the [new models](https://spacy.io/models/). 

The question @honnibal mentioned is still unresolved – see #593 (will merging this issue with #593 to keep things in one place). We're still working on finding the best solution.
