### ISSUE TITLE
Vocab Issue

### ISSUE THREAD

**Issue by lordsoffallen** [explosion/spaCy#13252]
## How to reproduce the behaviour

![image](https://github.com/explosion/spaCy/assets/20232088/0174a4e4-b2aa-44fb-b7af-b817abc88dba)
I am trying to find a word in the vocab and testing the example provided in the documentation. However I see that word apple is not in the vocab. Am I doing something wrong here? How can I check if a word exist in the vocab?

## Info about spaCy

- **spaCy version:** 3.7.2
- **Platform:** Linux-5.15.133+-x86_64-with-glibc2.31
- **Python version:** 3.10.12
- **Pipelines:** en_core_web_sm (3.7.1), en_core_web_lg (3.7.1)

**Comment by danieldk** [comment]
Reference to docs with the example: https://spacy.io/api/vocab#contains

**Comment by svlandeg** [comment]
You're right - this is confusing and the example is not complete. It sort of just assumes that at some point, the pipeline has seen the word "apple" because it's so common.

I fixed the example in the following PR: https://github.com/explosion/spaCy/pull/13273

If you try this, you'll see it works, because the `Vocab` works as a sort of cache.

**Comment by lordsoffallen** [comment]
hey @danieldk @svlandeg,

Thanks for the update. My question would be how can i access a let's say english vocab of a model. In nltk we can just download this and it has about 250k words there i believe. Is there a way to get a whole vocabulary in spacy? To me that's still not clear
