### ISSUE TITLE
"relcl" dependency label

### ISSUE THREAD

**Issue by Manslow** [explosion/spaCy#1903]
I'm using the annotations listed in https://spacy.io/api/annotation to define expected features for a model I am making but during parsing I find unlisted features such as the dependency label 'relcl'. This is also not located in symbols.py.

**Comment by honnibal** [comment]
Thanks. The `relcl` tag indicates a relative clause. We'll add it to the symbols table, but this can change the integer coding, so it will be delayed until new models are trained for the v2.1.0 release, which will likely be made next month.

**Comment by ines** [comment]
Fixed in dd9b0945af0cb2439d3d707429ae026a4aa6f8f5!

**Comment by IrfanKhanTanoli** [comment]
After update still it shows the error:

>>> import spacy
>>> from spacy.symbols import relcl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'relcl'
>>>


Regards
Irfan Tanoli


Irfan Khan Tanoli

PhD in Computer Science

Gran Sasso Science Institute

L'Aquila, Italy

**Comment by IrfanKhanTanoli** [comment]
Any update on this issue?

**Comment by ChangeMyName** [comment]
the symbols module still missing relcl. however the following works:
`            if (token.dep == 7972625988311165362):
                entities.append(token.head.text)`
