### ISSUE TITLE
Dep visualizer different from output

### ISSUE THREAD

**Issue by lizhao1993** [explosion/spaCy#2636]
For some content, dep visualizer is showing wrong results. Actual parser output is still correct.
Example attached-only produces error when the whole story is visualized. Specifically in the sentence:
"In the center is the house of Senex, who lives there with wife Domina, son Hero, and several slaves, including head slave Hysterium and the musical's main character Pseudolus."

(Incorrect)Visualizer says "Pseudolus"(NOUN) 's parent is "is"(VERB)  and relationship is PUNCT
(Correct)Output says "Pseudolus" (NOUN)'s parent is "Hysterium" (PROPN) and relationship is CONJ

## How to reproduce the behaviour
import spacy
from spacy import displacy
nlp = spacy.load('en_core_web_lg')

plot = "In ancient Rome, some neighbors live in three adjacent houses. In the center is the house of Senex, who lives there with wife Domina, son Hero, and several slaves, including head slave Hysterium and the musical's main character Pseudolus. A slave belonging to Hero, Pseudolus wishes to buy, win, or steal his freedom. One of the neighboring houses is owned by Marcus Lycus, who is a buyer and seller of beautiful women; the other belongs to the ancient Erronius, who is abroad searching for his long-lost children (stolen in infancy by pirates). One day, Senex and Domina go on a trip and leave Pseudolus in charge of Hero. Hero confides in Pseudolus that he is in love with the lovely Philia, one of the courtesans in the House of Lycus (albeit still a virgin). Pseudolus promises to help him win Philia's love in exchange for his own freedom. Unfortunately (as the two find out when they pay a visit on Lycus), Philia has been sold to the renowned warrior Miles Gloriosus, who is expected to claim her very soon. Pseudolus, an excellent liar, uses Philia's cheery disposition to convince Lycus that she has picked up a plague from Crete, which causes its victims to smile endlessly in its terminal stages. By offering to isolate her in Senex's house, he is able to give Philia and Hero some time alone together, and the two fall in love. But Philia insists that, even though she is in love with Hero, she must honor her contract with the Captain, for "that is the way of a courtesan". To appease her, he tells her to wait ("that's what virgins do best, isn't it. ") inside, and that he will have the captain knock three times when he arrives. Pseudolus comes up with a plan to slip Philia a sleeping potion that will render her unconscious. He will then tell Lycus that she has died of the Cretan plague, and will offer to remove the body. Hero will come along, and they will stow away on a ship headed for Greece. Satisfied with his plan, Pseudolus steals Hysterium's book of potions and has Hero read him the recipe for the sleeping potion; the only ingredient he lacks is "mare's sweat", and Pseudolus goes off in search of some. Unexpectedly, Senex returns home early from his trip, and knocks three times on his own door. Philia comes out of the house, and, thinking that Senex is the Captain, offers herself up to him. Surprised but game, Senex instructs Philia to wait in the house for him, and she does. Hysterium arrives to this confusion, and tells Senex that Philia is the new maid that he has hired. Pseudolus returns, having procured the necessary mare's sweat; seeing that Senex has returned unexpectedly and grasping the need to keep him out of the way, Pseudolus discreetly sprinkles some of the horse-sweat onto him, then suggests that the road trip has left Senex in dire need of a bath. Taking the bait, Senex instructs Hysterium to draw him a bath in the long-abandoned house of Erronius. But while this is happening, Erronius returns home, finally having given up the search for his long-lost children. Hysterium, desperate to keep him out of the house where his master is bathing, tells the old man that his house has become haunted – a story seemingly confirmed by the sound of Senex singing in his bath. Erronius immediately determines to have a soothsayer come and banish the spirit from his house, and Pseudolus obligingly poses as one, telling Erronius that, in order to banish the spirit, he must travel seven times around the seven hills of Rome (thus keeping the old man occupied and out of the way for quite a while). When Miles Gloriosus arrives to claim his courtesan-bride, Pseudolus hides Philia on the roof of Senex's house; told that she has "escaped," Lycus is terrified to face the Captain's wrath. Pseudolus offers to impersonate Lycus and talk his way out of the mess but, his ingenuity flagging, he ends up merely telling the Captain that Philia has disappeared, and that he, "Lycus", will search for her. Displeased and suspicious, Miles insists that his soldiers accompany Pseudolus, but the wily slave loses them in Rome's winding streets. Complicating matters further, Domina returns from her trip early, suspicious that her husband Senex is "up to something low". She disguises herself in virginal white robes and a veil (much like Philia's) to try to catch Senex being unfaithful. Pseudolus convinces Hysterium to help him by dressing in drag and pretending to be Philia, "dead" from the plague. Unfortunately, it turns out that Miles Gloriosus has just returned from Crete, where there is of course no actual plague. With the ruse thus revealed, the main characters run for their lives, resulting in a madcap chase across the stage with both Miles and Senex pursuing all three "Philia"s (Domina, Hysterium, and the actual Philia – all wearing identical white robes and veils). Meanwhile, the courtesans from the house of Marcus Lycus &ndash; who had been recruited as mourners at "Philia"'s ersatz funeral &ndash; have escaped, and Lycus sends his eunuchs out to bring them all back, adding to the general pandemonium. Finally, the Captain's troops are able to round everyone up. His plot thoroughly unraveled, Pseudolus appears to be in deep trouble – but Erronius, completing his third circuit of the Roman hills, shows up fortuitously to discover that Miles Gloriosus and Philia are wearing matching rings which mark them as his long-lost children. Philia's betrothal to the Captain is obviously nullified by the unexpected revelation that he's her brother. Philia weds Hero; Pseudolus gets his freedom and the lovely courtesan Gymnasia; Gloriosus receives twin courtesans to replace Philia; and Erronius is reunited with his children. A happy ending prevails for all – except for poor Senex, stuck with his shrewish wife Domina."

doc = nlp(plot)
displacy.serve(doc, style='dep')

## Info about spaCy

* **spaCy version:** 2.0.11
* **Platform:** Darwin-17.5.0-x86_64-i386-64bit
* **Python version:** 3.6.5
* **Models:** en_core_web_lg, en

**Comment by ines** [comment]
> For some content, dep visualizer is showing wrong results. Actual parser output is still correct.

Hmm, do you have a shorter example that's easier to reproduce? The visualizer output should always be identical to what the parser predicts, because it really just renders whatever the model outputs. When you compared the results, did you process the exact same text? It's sometimes possible that the predictions differ depending on  the context – for example, if you're only processing a half-sentence or a sentence without punctuation.

> spaCy version: 2.0.11

Could you try upgrading to `v2.0.12` and see if that resolves the problem? We pushed a small fix to the visualizer that might be related.

**Comment by lizhao1993** [comment]
I've updated to v2.0.12, still see this issue. 
I'm fairly sure the output and the visualizer was processing the same text since I was getting the output from putting a breakpoint in the code.
Sorry I don't have a shorter sample. :( If I just use that one sentence it seems to work with no bugs. Here is the (partial) pdf for visualizer if that helps.
[displaCy.pdf](https://github.com/explosion/spaCy/files/2267377/displaCy.pdf)

**Comment by ines** [comment]
Thanks! From looking at the PDF, it's possible that the problem here is the length of the text... on really long texts that also have *very* long dependencies, fitting all arcs and different levels of arcs becomes difficult, so you end up with squished arrows and bad alignment.

So in general, I'd recommend visualising shorter texts, or visualising a long text as individual sentences instead. In the latest version, the visualizer now also supports passing in `Span` objects. The `doc.sents` are `Span`s, so you could do something like this:

```python
doc = nlp(plot)
displacy.serve(list(doc.sents), style='dep')
```

This will render the text like this (which is also easier to read, imo):

![](https://user-images.githubusercontent.com/13643239/43839254-ee39e9e6-9b1d-11e8-92ff-02aad6f6e06c.png)

(I might add a note about this to the docs, since it's potentially useful for others as well!)

**Comment by lizhao1993** [comment]
Okay, will do, thanks!

**Comment by ines** [comment]
Yes, this definitely makes it easier to look at the dependencies! Could you point me to the  tree in the PDF that I should be looking at?

> (Incorrect)Visualizer says "Pseudolus"(NOUN) 's parent is "is"(VERB) and relationship is PUNCT
> (Correct)Output says "Pseudolus" (NOUN)'s parent is "Hysterium" (PROPN) and relationship is CONJ

I've been trying to find a "Pseudolus" attached to "is", but I couldn't immediately see it?

**Comment by lizhao1993** [comment]
In the second sentence:
"In the center 

> is

 the house of Senex, who lives there with wife Domina, son Hero, and several slaves, including head slave Hysterium and the musical's main character 

> Pseudolus

."
Here 'is' is the parent of Pseudolus (arrow going from 'is' to Pseudolus, with relationship being PUNCT)

**Comment by ines** [comment]
Okay, I think I found it: there seems to be a problem caused by the visualizer merging punctuation, but not removing the related dependency arc. So the `"Pseudolus."` token now gets both dependencies for `"Pseudolus"` and `"."`, causing the confusing visual output.

Interestingly, this only seems to occur on very long dependencies, and if the trailing punctuation is followed by at least one other token. (In your case, there seems to be a single space token after each sentence.)

As a workaround, you can set the punctuation merging to `False` like this ([see here](https://spacy.io/api/top-level#options-dep) for all available options):

```python
displacy.serve(list(doc.sents), style='dep', options={'collapse_punct': False})
```

**Comment by lizhao1993** [comment]
Works now, thanks! 👍
