### ISSUE TITLE
Error assigning label ID to span

### ISSUE THREAD

**Issue by jam878** [explosion/spaCy#2984]
## How to reproduce the behaviour
Using same entity matcher class that can be found here: https://spacy.io/usage/processing-pipelines#section-custom-components
I'm passing a tuple of keywords into this matcher using this bit of code (in this example, the entity name variable is called rule_name and is set to 'CANCER')
```
if 'entity_matcher' in nlp.pipe_names:
	nlp.remove_pipe('entity_matcher')
entity_matcher = EntityMatcher(nlp, rule_keywords, rule_name)
nlp.add_pipe(entity_matcher, after='ner')
```
When I go to load text into the model I get this error:
```
Traceback (most recent call last):
  File "C:/Users/jamorg/PycharmProjects/Model Training/new_model.py", line 63, in <module>
    model_name=model_name, print_all_ents=print_all_ents, create_visualizations=create_visualizations
  File "C:\Users\jamorg\PycharmProjects\Model Training\trainer\train_model.py", line 166, in train_model
    doc = nlp(text)  # Load sentence into nlp module
  File "C:\Users\jamorg\PycharmProjects\Model Training\venv\lib\site-packages\spacy\language.py", line 346, in __call__
    doc = proc(doc)
  File "C:\Users\jamorg\PycharmProjects\Model Training\trainer\train_model.py", line 21, in __call__
    span = Span(doc, start, end, label=match_id)
  File "span.pyx", line 68, in spacy.tokens.span.Span.__cinit__
ValueError: [E084] Error assigning label ID 18446744072199394250 to span: not in StringStore.
```
I've seen some people have success with adding the entity name to vocab with `nlp.vocab.strings.add(entity_name)` but it doesn't change anything on my end

## Your Environment
* **spaCy version:** 2.0.16
* **Platform:** Windows-7-6.1.7601-SP1
* **Python version:** 3.7.0
* **Models:** en_core_web_md, en_core_web_sm

**Comment by ines** [comment]
Could you post a bit more of your code and how you set up the `nlp` object? Is it possible that you're not sharing the same `nlp.vocab` across your components/functions? For example, are you constructing the `Matcher` with the same vocab you're processing the text with?

According to the error, the ID `18446744072199394250` can't be resolved back to a string in the string store. When you add the matcher rule (and *especially* when you add the string manually), this shouldn't be the case and there should be a string present for that ID.

**Comment by jam878** [comment]
For the PhraseMatcher I am using the same class as provided in the documentation examples
```
class EntityMatcher(object):
	name = 'entity_matcher'

	def __init__(self, nlp, terms, label):
		patterns = [nlp(text) for text in terms]
		self.matcher = PhraseMatcher(nlp.vocab)
		self.matcher.add(label, None, *patterns)

	def __call__(self, doc):
		matches = self.matcher(doc)
		for match_id, start, end in matches:
			span = Span(doc, start, end, label=match_id)
			doc.ents = list(doc.ents) + [span]
		return doc
```
I have a tuple of keywords related to cancer and a label name of 'CANCER'
After using nlp.update to train the model for a certain amount of time I add the entity_matcher component to the pipeline with this bit of code
```
# Create entity matcher for specified rule
if 'entity_matcher' in nlp.pipe_names:
	nlp.remove_pipe('entity_matcher')
for keyword in matcher_keywords:
	nlp.vocab.strings.add(keyword)
nlp.vocab.strings.add(label_name)
entity_matcher = EntityMatcher(nlp, terms=matcher_keywords, label=label_name)
nlp.add_pipe(entity_matcher)
```
I made sure to explicitly add both the label name to the vocab strings. When I check the strings.json file in the model directory, all the words I wish to match are there.
After I load my text using
`doc = nlp(text)`
I get the error message described in the original post.
I'm very confused since the strings appear in the strings file but cannot be found when I try to process the text.
Thanks for your help, apologies if I am unclear about my issue, I am a bit of a beginner when it comes to this stuff.

**Comment by ines** [comment]
No worries – it's definitely not immediately obvious why this is happening!

I just tried it in the latest `spacy-nightly` version (upcoming `v2.1.0`) and I couldn't reproduce the issue, so it's possible that whatever caused this is already resolved. So if you like, you could set up a new virtual environment, install `spacy-nightly` from pip, download the new model and try running your code again?

**Comment by jam878** [comment]
I just tried to install spacy-nightly but I am getting an error about the setup.py file for blis failing to install

The errors I am getting are on the newest version of Spacy

I've updated my original script but I'm still having the problem.
Here is the code for setting up my matcher in the main function: 
```
stringstore = StringStore()
stringstore.add(rule_name)
nlp.vocab.strings.add(rule_name)
patterns = [nlp(keyword) for keyword in rule_keywords]
matcher = PhraseMatcher(nlp.vocab)
matcher.add(rule_name, None, *patterns)
```
I made sure to manually add my rule_name (in this case 'CANCER') to the string store and to nlp.vocab for the sake of redundancy. 
When I process text with
```
doc = nlp(text)
matches = matcher(doc)
print(matches)
for match_id, start, end in matches:
	span = Span(doc, start, end, label=match_id)
	doc.ents = list(doc.ents) + [span]
```
I am able to properly recognize an entity and print out the label ID in addition to the start and end tokens but I still get
`ValueError: [E084] Error assigning label ID 18446744072199394250 to span: not in StringStore.`
I can tell that the label ID is in reference to 'CANCER' because it's the same ID that is printed out when I print the matches from the document. 
I'm confused because the only code in between creating the matcher and processing text is an unrelated function that reads a text file so it's not an issue with not sharing the vocab between components. Since I manually added the string to StringStore and the matcher itself works properly, I don't understand where the error could be coming from.

**Comment by ines** [comment]
> I just tried to install spacy-nightly but I am getting an error about the setup.py file for blis failing to install

Did you install it from pip via `pip install spacy-nightly` or did you build it from source? I'd be interested in seeing the error (maybe in a separate issue), because it might indicate some problem with our new `blis` package on Windows.

> I am able to properly recognize an entity and print out the label ID in addition to the start and end tokens but I still get `ValueError: [E084] Error assigning label ID 18446744072199394250 to span: not in StringStore`.

Hmmm, this is really strange 🤔 You definitely shouldn't have to jump through so many hoops. I tried to break down the code into a simple example that should cover the core of what you're trying to do, right?

```python
from spacy.lang.en import English
from spacy.matcher import PhraseMatcher
from spacy.tokens import Span

nlp = English()
matcher = PhraseMatcher(nlp.vocab)
matcher.add('CANCER', None, nlp("cancer"))
doc = nlp("text about cancer")
for match_id, start, end in matcher(doc):
    print(Span(doc, start, end, label=match_id))
```

Does this code work for you? I just ran it in the latest `v2.0.18` and it worked for me.

**Comment by jam878** [comment]
I was trying to install from `pip install spacy-nightly` on a new virtualenv instance when I got the error, I'll open a new issue with the complete log when I get a chance.

As for the code you provided, that is essentially what I am trying to do and I got the exact same error trying to run that on a clean install of the latest official spacy version.

**Comment by jam878** [comment]
Ok, I think this issue traces back to the fact that was using 32-bit Python instead of 64-bit. After upgrading, uninstalling the old versions and reconfiguring my virtualenv I was able to get everything to work on the latest official version.
This was a confusing issue beginning to end, I really appreciate the help.

**Comment by ines** [comment]
Thanks for the update and sorry this was so frustrating! Really a bizarre and subtle issue, but good to know for the future! 👍
