### ISSUE TITLE
cli download fails with unexpected keyword argument 'no_args_is_help': incompatible click version

### ISSUE THREAD

**Issue by apmechev** [explosion/spaCy#7160]
## How to reproduce the behaviour

Command:
```bash
 python -m spacy download nl_core_news_lg
```
Returns exception ❌:

```python
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/spacy/__main__.py", line 4, in <module>
    setup_cli()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/spacy/cli/_util.py", line 67, in setup_cli
    command = get_command(app)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/typer/main.py", line 232, in get_command
    click_command = get_group(typer_instance)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/typer/main.py", line 218, in get_group
    group = get_group_from_info(TyperInfo(typer_instance))
  File "/home/ubuntu/.local/lib/python3.8/site-packages/typer/main.py", line 349, in get_group_from_info
    command = get_command_from_info(command_info=command_info)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/typer/main.py", line 425, in get_command_from_info
    command = cls(  # type: ignore
TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'
```
Running the download in the python shell doesn't return any issues ✔:
```python
>>> import spacy
>>> from spacy.cli.download import download
>>> download(model="nl_core_news_lg")

```
## Your Environment

* Operating System: `Ubuntu 20.04.2 LTS`
* Python Version Used: `Python 3.8.5 (default, Jul 28 2020, 12:59:40)`
* spaCy Version Used: `3.0.3`

* Installation Instructions: 
```
python -m pip install boto3 \
    tensorflow==2.3.1 \
    joblib \
    jsonschema \
    pandas \
    numpy \
    scikit-learn\
    spacy \
    flask \
```

<details>
<summary>Environment Information: </summary>

|Package | Version |
|---------------------- |--------------------|
|absl-py |0.11.0 |
|astunparse |1.6.3 |
|attrs |19.3.0 |
|Automat |0.8.0 |
|awscli |1.18.69 |
|blinker |1.4 |
|blis |0.7.4 |
|boto3 |1.17.12 |
|botocore |1.20.12 |
|cachetools |4.2.1 |
|catalogue |2.0.1 |
|certifi |2019.11.28 |
|chardet |3.0.4 |
|click |7.1.2 |
|cloud-init |20.4 |
|colorama |0.4.3 |
|command-not-found |0.3 |
|configobj |5.0.6 |
|constantly |15.1.0 |
|cryptography |2.8 |
|cymem |2.0.5 |
|dbus-python |1.2.16 |
|distro |1.4.0 |
|distro-info |0.23ubuntu1 |
|docutils |0.16 |
|ec2-hibinit-agent |1.0.0 |
|en-core-web-sm |3.0.0 |
|entrypoints |0.3 |
|Flask |1.1.2 |
|gast |0.3.3 |
|google-auth |1.27.0 |
|google-auth-oauthlib |0.4.2 |
|google-pasta |0.2.0 |
|grpcio |1.35.0 |
|h5py |2.10.0 |
|hibagent |1.0.1 |
|httplib2 |0.14.0 |
|hyperlink |19.0.0 |
|idna |2.8 |
|importlib-metadata |1.5.0 |
|incremental |16.10.1 |
|itsdangerous |1.1.0 |
|Jinja2 |2.10.1 |
|jmespath |0.9.4 |
|joblib |1.0.1 |
|jsonpatch |1.22 |
|jsonpointer |2.0 |
|jsonschema |3.2.0 |
|Keras-Preprocessing |1.1.2 |
|keyring |18.0.1 |
|language-selector |0.1 |
|launchpadlib |1.10.13 |
|lazr.restfulclient |0.14.2 |
|lazr.uri |1.0.3 |
|Markdown |3.3.3 |
|MarkupSafe |1.1.0 |
|more-itertools |4.2.0 |
|murmurhash |1.0.5 |
|netifaces |0.10.4 |
|nl-core-news-lg |3.0.0 |
|numpy |1.20.1 |
|oauthlib |3.1.0 |
|olefile |0.46 |
|opt-einsum |3.3.0 |
|packaging |20.9 |
|pandas |1.2.2 |
|pathy |0.4.0 |
|pexpect |4.6.0 |
|Pillow |7.0.0 |
|pip |20.0.2 |
|preshed |3.0.5 |
|protobuf |3.15.1 |
|pyasn1 |0.4.2 |
|pyasn1-modules |0.2.1 |
|pydantic |1.7.3 |
|Pygments |2.3.1 |
|PyGObject |3.36.0 |
|PyHamcrest |1.9.0 |
|PyJWT |1.7.1 |
|pymacaroons |0.13.0 |
|PyNaCl |1.3.0 |
|pyOpenSSL |19.0.0 |
|pyparsing |2.4.7 |
|pyrsistent |0.15.5 |
|pyserial |3.4 |
|python-apt |2.0.0+ubuntu0.20.4.4 |
|python-dateutil |2.7.3 |
|python-debian |0.1.36ubuntu1 |
|pytz |2021.1 |
|PyYAML |5.3.1 |
|requests |2.22.0 |
|requests-oauthlib |1.3.0 |
|requests-unixsocket |0.2.0 |
|roman |2.0.0 |
|rsa |4.0 |
|s3transfer |0.3.3 |
|scikit-learn |0.24.1 |
|scipy |1.6.1 |
|SecretStorage |2.3.1 |
|service-identity |18.1.0 |
|setuptools |45.2.0 |
|simplejson |3.16.0 |
|six |1.14.0 |
|smart-open |3.0.0 |
|sos |4.0 |
|spacy |3.0.3 |
|spacy-legacy |3.0.1 |
|srsly |2.4.0 |
|ssh-import-id |5.10 |
|systemd-python |234 |
|tensorboard |2.4.1 |
|tensorboard-plugin-wit |1.8.0 |
|tensorflow |2.3.1 |
|tensorflow-estimator |2.3.0 |
|termcolor |1.1.0 |
|thinc |8.0.1 |
|threadpoolctl |2.1.0 |
|tqdm |4.57.0 |
|Twisted |18.9.0 |
|typer |0.3.2 |
|ubuntu-advantage-tools |20.3 |
|ufw |0.36 |
|unattended-upgrades |0.1 |
|urllib3 |1.25.8 |
|wadllib |1.3.3 |
|wasabi |0.8.2 |
|Werkzeug |1.0.1 |
|wheel |0.34.2 |
|wrapt |1.12.1 |
|zipp |1.0.0 |
|zope.interface |4.7.1 |

</details>

**Comment by svlandeg** [comment]
Could you check which version of `typer` you have installed? It should be `>=0.3.0`

**Comment by apmechev** [comment]
`typer` is the latest version available in pypi: `0.3.2`. I've also added a full list of packages in the original post (at the bottom)

**Comment by svlandeg** [comment]
Oh, I hadn't seen that list, that's extremely useful, thanks ;-)

Anyway we looked into this a bit more with @tiangolo as well (author of `typer`) an we're quite puzzled. The error does seem to indicate an incompatibility with click/typer, but your packages list on the other hand seems fine and up-to-date.

Is there any chance you could start from a clean, fresh virtual environment, install spaCy from scratch, and try the `download` command again?

**Comment by apmechev** [comment]
Hi again, 

Here's the repro instructions on a new t2.micro ECS running Ubuntu 20.04

```bash
    1  sudo apt-get update
    2  sudo apt-get upgrade
    5  sudo apt-get install python3-pip
    9  python3 -m pip install boto3     joblib     jsonschema     pandas     numpy     scikit-learn    spacy     flask
   13  python3 -m spacy download nl_core_news_lg
   14  history
```

the pip install output is bellow:

<details>
<summary>Pip output </summary>
Collecting boto3
  Using cached boto3-1.17.18-py2.py3-none-any.whl (130 kB)
Collecting joblib
  Downloading joblib-1.0.1-py3-none-any.whl (303 kB)
     |████████████████████████████████| 303 kB 19.6 MB/s
Requirement already satisfied: jsonschema in /usr/lib/python3/dist-packages (3.2.0)
Collecting pandas
  Downloading pandas-1.2.2-cp38-cp38-manylinux1_x86_64.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 24.9 MB/s
Collecting numpy
  Downloading numpy-1.20.1-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
     |████████████████████████████████| 15.4 MB 36.0 MB/s
Collecting scikit-learn
  Downloading scikit_learn-0.24.1-cp38-cp38-manylinux2010_x86_64.whl (24.9 MB)
     |████████████████████████████████| 24.9 MB 32.3 MB/s
Collecting spacy
  Downloading spacy-3.0.3-cp38-cp38-manylinux2014_x86_64.whl (12.9 MB)
     |████████████████████████████████| 12.9 MB 34.9 MB/s
Collecting flask
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 458 kB/s
Collecting s3transfer<0.4.0,>=0.3.0
  Downloading s3transfer-0.3.4-py2.py3-none-any.whl (69 kB)
     |████████████████████████████████| 69 kB 9.1 MB/s
Collecting botocore<1.21.0,>=1.20.18
  Downloading botocore-1.20.18-py2.py3-none-any.whl (7.3 MB)
     |████████████████████████████████| 7.3 MB 30.1 MB/s
Collecting jmespath<1.0.0,>=0.7.1
  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
     |████████████████████████████████| 227 kB 40.8 MB/s
Collecting pytz>=2017.3
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 31.8 MB/s
Collecting threadpoolctl>=2.0.0
  Downloading threadpoolctl-2.1.0-py3-none-any.whl (12 kB)
Collecting scipy>=0.19.1
  Downloading scipy-1.6.1-cp38-cp38-manylinux1_x86_64.whl (27.3 MB)
     |████████████████████████████████| 27.3 MB 30.9 MB/s
Collecting murmurhash<1.1.0,>=0.28.0
  Downloading murmurhash-1.0.5-cp38-cp38-manylinux2014_x86_64.whl (20 kB)
Collecting preshed<3.1.0,>=3.0.2
  Downloading preshed-3.0.5-cp38-cp38-manylinux2014_x86_64.whl (130 kB)
     |████████████████████████████████| 130 kB 42.8 MB/s
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from spacy) (45.2.0)
Collecting thinc<8.1.0,>=8.0.0
  Downloading thinc-8.0.1-cp38-cp38-manylinux2014_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 30.5 MB/s
Collecting spacy-legacy<3.1.0,>=3.0.0
  Downloading spacy_legacy-3.0.1-py2.py3-none-any.whl (7.0 kB)
Collecting typer<0.4.0,>=0.3.0
  Downloading typer-0.3.2-py3-none-any.whl (21 kB)
Collecting catalogue<2.1.0,>=2.0.1
  Downloading catalogue-2.0.1-py3-none-any.whl (9.6 kB)
Collecting pydantic<1.8.0,>=1.7.1
  Downloading pydantic-1.7.3-cp38-cp38-manylinux2014_x86_64.whl (12.2 MB)
     |████████████████████████████████| 12.2 MB 33.6 MB/s
Collecting pathy
  Downloading pathy-0.4.0-py3-none-any.whl (36 kB)
Collecting blis<0.8.0,>=0.4.0
  Downloading blis-0.7.4-cp38-cp38-manylinux2014_x86_64.whl (9.8 MB)
     |████████████████████████████████| 9.8 MB 33.1 MB/s
Collecting cymem<2.1.0,>=2.0.2
  Downloading cymem-2.0.5-cp38-cp38-manylinux2014_x86_64.whl (35 kB)
Collecting packaging>=20.0
  Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 8.5 MB/s
Collecting tqdm<5.0.0,>=4.38.0
  Downloading tqdm-4.58.0-py2.py3-none-any.whl (73 kB)
     |████████████████████████████████| 73 kB 2.2 MB/s
Collecting srsly<3.0.0,>=2.4.0
  Downloading srsly-2.4.0-cp38-cp38-manylinux2014_x86_64.whl (458 kB)
     |████████████████████████████████| 458 kB 33.4 MB/s
Collecting wasabi<1.1.0,>=0.8.1
  Downloading wasabi-0.8.2-py3-none-any.whl (23 kB)
Requirement already satisfied: jinja2 in /usr/lib/python3/dist-packages (from spacy) (2.10.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/lib/python3/dist-packages (from spacy) (2.22.0)
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 38.1 MB/s
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: click>=5.1 in /usr/lib/python3/dist-packages (from flask) (7.0)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/lib/python3/dist-packages (from botocore<1.21.0,>=1.20.18->boto3) (1.25.8)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7.3->pandas) (1.14.0)
Collecting smart-open<4.0.0,>=2.2.0
  Downloading smart_open-3.0.0.tar.gz (113 kB)
     |████████████████████████████████| 113 kB 40.4 MB/s
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
     |████████████████████████████████| 67 kB 8.6 MB/s
Building wheels for collected packages: smart-open
  Building wheel for smart-open (setup.py) ... done
  Created wheel for smart-open: filename=smart_open-3.0.0-py3-none-any.whl size=107092 sha256=057391ae280881bd70247c7ec5eb0a10966bc089c06171b935e3c96e66027eab
  Stored in directory: /home/ubuntu/.cache/pip/wheels/11/73/9a/f91ac1f1816436b16423617c5be5db048697ff152a9c4346f2
Successfully built smart-open
ERROR: typer 0.3.2 has requirement click<7.2.0,>=7.1.1, but you'll have click 7.0 which is incompatible.
Installing collected packages: jmespath, python-dateutil, botocore, s3transfer, boto3, joblib, numpy, pytz, pandas, threadpoolctl, scipy, scikit-learn, murmurhash, cymem, preshed, catalogue, srsly, pydantic, blis, wasabi, thinc, spacy-legacy, typer, smart-open, pathy, pyparsing, packaging, tqdm, spacy, Werkzeug, itsdangerous, flask
  WARNING: The scripts f2py, f2py3 and f2py3.8 are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pathy is installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tqdm is installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script spacy is installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script flask is installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed Werkzeug-1.0.1 blis-0.7.4 boto3-1.17.18 botocore-1.20.18 catalogue-2.0.1 cymem-2.0.5 flask-1.1.2 itsdangerous-1.1.0 jmespath-0.10.0 joblib-1.0.1 murmurhash-1.0.5 numpy-1.20.1 packaging-20.9 pandas-1.2.2 pathy-0.4.0 preshed-3.0.5 pydantic-1.7.3 pyparsing-2.4.7 python-dateutil-2.8.1 pytz-2021.1 s3transfer-0.3.4 scikit-learn-0.24.1 scipy-1.6.1 smart-open-3.0.0 spacy-3.0.3 spacy-legacy-3.0.1 srsly-2.4.0 thinc-8.0.1 threadpoolctl-2.1.0 tqdm-4.58.0 typer-0.3.2 wasabi-0.8.2

</details>

**Comment by apmechev** [comment]
✅ Resolved ✅

Solution was to manually update the  `click` package:

` pip3 install click --upgrade`

**Comment by svlandeg** [comment]
Oh that's strange, because you did list `click` 7.1.2 in your environment?
Python and dependencies....... ;-)

Anyway happy to hear you got it resolved, and thanks for reporting back!

**Comment by mrmechko** [comment]
For anyone coming to this solution now, simply running `pip install click --upgrade` will install version `>=8.0.1` which also doesn't work. 

Make sure to specify version `7.1.2` with `pip install click==7.1.2`

**Comment by aniruddhakal** [comment]
> white_check_mark Resolved white_check_mark
> 
> Solution was to manually update the `click` package. No need to change anything else
> 
> ` pip3 install click --upgrade`

Worked upgrade to click==8.0.1
Thanks!

**Comment by svlandeg** [comment]
Thanks for the note. From [typer 0.4](https://github.com/tiangolo/typer/releases/tag/0.4.0), Click 8 is supported. From [spaCy 3.1.3](https://github.com/explosion/spaCy/releases/tag/v3.1.3), we've expanded the typer upper pin, but for earlier version of spaC you can probably still get away with upgrading `typer` to 0.4 to be able to use the newest Click.
