### ISSUE TITLE
Error in merge_phrases 

### ISSUE THREAD

**Issue by vladimircape** [explosion/spaCy#975]
Got such error

> "Error calculating span: Can't find start"

When i tried to put such text

> "What factors is iShares 1-3 Year Credit Bond exposed with"

code of merge_phrases

```
def merge_phrases(matcher, doc, i, matches):
    '''
    Merge a phrase. We have to be careful here because we'll change the token indices.
    To avoid problems, merge all the phrases once we're called on the last match.
    '''
    if i != len(matches)-1:
        return None
    spans = [(ent_id, label, doc[start : end]) for ent_id, label, start, end in matches]
    for ent_id, label, span in spans:
        span.merge('NNP' if label else span.root.tag_, span.text, settings.nlp.vocab.strings[label])
```

**Comment by honnibal** [comment]
I think this means you've supplied a start character offset that doesn't correspond to a token offset. Could you give the values being passed to the `merge_phrases` function?

**Comment by vladimircape** [comment]
Sure 
1.error below i fixed by such code 

`spans = [(ent_id, label, doc[start : end]) for ent_id, label, start, end in matches if len(doc[start : end])>1]`

Also question ,how to decline recognition of some type of entities, for example i don't need CARDINAL

2.Right now i only have problem with such text

> What factors is Morley Stable Value Fund Class 55 - I(2) exposed with in Virgin Islands of the United States?

ent_id
label
 doc[start : end]

`============
812670
350457
3
Morley Stable Value Fund Class 55 - I(2)
812670
350457
3
Morley Stable Value Fund Class 55 - I(2)
777431
353773
15
Virgin Islands of the United States
777415
353773
19
United States
777415
353773
19
United States
`

**Comment by vladimircape** [comment]
Other sample

`What about BB&T Corp`

message": "Error : Error calculating span: Can't find start101"

i tried to debug like these
```

spans = [(ent_id, label, doc[start: end]) for ent_id, label, start, end in matches]
    dublicates = []
    for ent_id, label, start, end in matches:
        if str(ent_id)=='790907':
            print("-----------------")
            print(str(start))
            print(str(end))
            print(str(label))
            print(str(doc[start: end]))
            print("-----------------")
    for ent_id, label, span in spans:
        if ent_id not in dublicates:
            #dublicates.append(ent_id)
            print("******")
            print(str(ent_id))
            print(str(label))
            print(str(span.text))
            print("+++++")
            span.merge('NNP' if label else span.root.tag_, span.text, settings.nlp.vocab.strings[label])
```

and got 

> 
> -----------------
> 3
> 4
> 350457
> Corp
> -----------------
> -----------------
> 3
> 4
> 350457
> Corp
> -----------------
> ******
> 838308
> 188451
> BB&T
> +++++
> ******
> 838308
> 188451
> BB&T
> +++++
> ******
> 835899
> 188451
> BB&T Corp
> +++++
> ******
> 835899
> 188451
> BB&T Corp
> +++++
> ******
> 790907
> 350457
I used matchers and look that entitiy 790907 its broke

**Comment by vladimircape** [comment]
`span.text`
is empty to ent_id 790907

**Comment by vladimircape** [comment]
if temporary fix it by these

```
def merge_phrases(matcher, doc, i, matches):
    '''
    Merge a phrase. We have to be careful here because we'll change the token indices.
    To avoid problems, merge all the phrases once we're called on the last match.
    '''
    if i != len(matches)-1:
        return None

    #spans = [(ent_id, label, doc[start : end]) for ent_id, label, start, end in matches if len(doc[start : end])>1]
    spans = [(ent_id, label, doc[start: end]) for ent_id, label, start, end in matches]
    dublicates = []
    test = {}
    for ent_id, label, start, end in matches:
        test[start]={}
        test[start][end] = str(doc[start: end])

    for ent_id, label, span in spans:
        if ent_id not in dublicates:
            dublicates.append(ent_id)
            if str(doc[span.start: span.end])=="":
                text_value = test[span.start][span.end]
            else:
                text_value = span.text
            span.merge('NNP' if label else span.root.tag_, text_value, settings.nlp.vocab.strings[label])
```

**Comment by honnibal** [comment]
I'm having a lot of trouble following here. Is there still a problem?

It would help me a lot if you could describe the problems in a slightly more organised way. In particular the formatting on your logs makes them very difficult to read.

**Comment by vladimircape** [comment]
Hi, these temporary ugly solution helps me. i will refactor it little bit later, the problem was that smth 
`span.text`
was empty.
in these part of code, everything was ok 
`spans = [(ent_id, label, doc[start: end]) for ent_id, label, start, end in matches]`

but inside the last loop
`for ent_id, label, span in spans:`
it was empty because start parameter becomes somehow in a wrong value

it temporary fixed it by making duplicate of span text
